whedon.rb

Replaces #3 
/ cc @kyleniemeyer

Adding @lheagy to editors

---

Gemfile
Gemfile.lock
app.json
whedon.rb

This PR gives @whedon the ability to report the programming languages of the repository under review in the JOSS `PRE REVIEW` issues.
These languages are added as labels e.g.:
Fixes https://github.com/openjournals/joss/issues/318

Language tags

---

config/settings.yml
responses/goodbye.erb
whedon.rb

This PR adds a closing message from @whedon when a review is closed. This is what the message looks like:
In the future we should add a link to donate to JOSS/JOSE etc. but we don't yet have those links from NumFOCUS.
Fixes https://github.com/openjournals/joss/issues/314

Congratulations

---

whedon.rb

Fixes https://github.com/openjournals/whedon-api/issues/18

Switching to different GitHub APIs

---

config/settings.yml
responses/goodbye.erb
whedon.rb

Fixes https://github.com/openjournals/joss/issues/365
/ cc @danielskatz

Adding links to donate campaigns

---

responses/goodbye.erb

Slight tweak to language

---

responses/commands.erb
whedon.rb

👋 @parrish - moving this PR to the `openjournals/whedon-api` repo so I can try deploying this out on Heroku.
Replaces #24

Add multiple reviewers

---

responses/magic_word.erb
responses/missing_editor_reviewer.erb
whedon.rb

Fixes https://github.com/openjournals/joss/issues/199
/ cc @danielskatz

Removing bananas flag and adding better error handling

---

config/settings-production.yml
config/settings-test.yml
config_helper.rb
github.rb
spec/whedon_basics_spec.rb
whedon_api.rb
workers.rb

This PR is a small set of changes to extract some of the logic around setting configs/environment variables in background workers.

Extracting configs

---

.travis.yml
spec/doi_checker_spec.rb

This PR makes the Travis CI build pass:
- Fixed an error with the installed bundler version
- Fixed a failing spec

Fix Travis build

---

spec/whedon_api_spec.rb

This PR updates a failling spec to take into account the recently added `check references` comment. 
It should fix the build.

Update spec 

---

workers.rb

Fixes #73 
Fixes openjournals/joss#657

Better errors from preview

---

config/settings-production.yml
whedon_api.rb
workers.rb

Implements https://github.com/openjournals/joss/pull/694

Accept workflow tweak

---

responses/commands.erb
whedon_api.rb

Improving re-invite language

---

responses/reviewer_welcome.erb
responses/welcome.erb

This PR adds some words about the JOSS reduced service mode.
/ cc https://github.com/openjournals/joss/issues/733

Add warning about reduced service mode

---

Gemfile
Gemfile.lock
whedon_api.rb
workers.rb

Adding support for:
```
@whedon accept from branch custom_branch_name
```
and 
```
@whedon accept deposit=true from branch custom_branch_name
```

Adding support for custom branch when depositing

---

workers.rb

Partially addresses https://github.com/openjournals/whedon-api/issues/54

Check statement of need

---

whedon_api.rb

Check there is an editor assigned before assigning reviewers

---

spec/support/fixtures/whedon-accept-no-doi-on-review-issue-937.json
spec/support/fixtures/whedon-accept-with-doi-on-review-issue-938.json
whedon_api.rb

Moving editor accept to "recommend-accept"

---

whedon_api.rb
workers.rb

Count words and custom branch repo check

---

.github/workflows/tests.yml
.travis.yml
README.md

Add tests workflow

---

workers.rb

Adding code to check if adrn ORCID is present

---

spec/whedon_api_spec.rb
whedon_api.rb

this can be confusing and doesn't indicate what to do for authors

more explicit error message for archive
